site_name: psiflow
theme:
  favicon: icon.svg
  name: material
  font:
    text: overpass
  palette:
    primary: grey
    accent: pink
  logo: icon.svg
  features:
    #- navigation.expand
    - navigation.instant
    - navigation.tracking
      #- navigation.tabs
      #- navigation.tabs.sticky
      #- navigation.indexes
    - navigation.sections
    - toc.integrate

nav:
  - getting started: getting_started.md
  - workflow execution: workflow_execution.md
  - Documentation:
    - models:
      - NequIP: models_nequip.md
      - MACE: models_MACE.md
    - sampling:
      - random: sampling_random.md
      - optimization: sampling_optimization.md
      - dynamic: sampling_dynamic.md
      - bias: sampling_bias.md
    - reference:
      - EMT: reference_EMT.md
      - CP2K: reference_CP2K.md
      - VASP: reference_VASP.md
    - data: data.md
    - ensemble: ensemble.md
    - learning: learning.md
    - execution: execution.md
    - manager: manager.md
hide:
  - toc

plugins:
  - mkdocstrings
repo_url: https://github.com/svandenhaute/psiflow
