site_name: psiflow
theme:
  favicon: icon.svg
  name:
    material
    #font:
    #  text: overpass
  palette:
    primary: teal
    accent: yellow
    scheme: slate
  logo: icon.svg
  features:
    - content.code.copy
    - navigation.instant
    - navigation.tracking
      #- navigation.tabs
      #- navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - toc.follow

nav:
  - overview: index.md
  - atomic geometries: data.md
  - hamiltonians: hamiltonian.md
  - sampling: sampling.md
  - QM calculations: reference.md
  - ML potentials: model.md
  - online learning: learning.md
  - configuration: configuration.md

plugins:
  - mkdocstrings:
      python:
        docstring_style: google
    
repo_url: https://github.com/molmod/psiflow
markdown_extensions:
  - tables
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
