site_name: psiflow
theme:
  favicon: icon.svg
  name: material
    #font:
    #  text: overpass
  palette:
    primary: teal
    accent: teal
  logo: icon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - toc.integrate

nav:
  - Introduction: index.md
  - Overview: overview.md
  - Configuration: config.md
  - Examples: examples.md
  - Installation: installation.md
    #- Workflow execution: workflow_execution.md
    #- API:
    #  - Models:
    #    - NequIP: models/nequip.md
    #    - MACE: models/mace.md
    #  - Sampling:
    #    - Random: sampling/random.md
    #    - Optimization: sampling/optimization.md
    #    - Dynamic: sampling/dynamic.md
    #    - PLUMED: sampling/plumed_bias.md
    #  - Reference:
    #    - EMT: reference/EMT.md
    #    - CP2K: reference/CP2K.md
    #    - VASP: reference/VASP.md
    #  - Data: data.md
    #  - Ensemble: ensemble.md
    #  - Checks: checks.md
    #  - Learning: learning.md
    #  - Execution: execution.md
    #  - Experiment: experiment.md
hide:
  - toc

plugins:
  - mkdocstrings:
      python:
        docstring_style: google
    
repo_url: https://github.com/svandenhaute/psiflow
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
