---
ModelEvaluation:
  cores_per_worker: 12
  gpu: True
  max_simulation_time: 20
  slurm:
    partition: "gpu_rome_a100"
    account: "2023_070"
    nodes_per_block: 1
    cores_per_node: 48
    max_blocks: 1
    walltime: "12:00:00"
    scheduler_options: "#SBATCH --clusters=dodrio\n#SBATCH --gpus=4\n"
ModelTraining:
  cores_per_worker: 12
  gpu: true
  max_training_time: 40
  slurm:
    partition: "gpu_rome_a100"
    account: "2023_070"
    nodes_per_block: 1
    cores_per_node: 12
    max_blocks: 1
    walltime: "12:00:00"
    scheduler_options: "#SBATCH --clusters=dodrio\n#SBATCH --gpus=1\n"
CP2K:
  cores_per_worker: 64
  max_evaluation_time: 30
  slurm:
    partition: "cpu_rome"
    account: "starting_2024_030"
    nodes_per_block: 1
    cores_per_node: 64
    max_blocks: 50
    walltime: "06:00:00"
    scheduler_options: "#SBATCH --clusters=dodrio\n"
...
