---
ModelEvaluation:
  max_walltime: 0.3
  simulation_engine: 'openmm'
  gpu: false
ModelTraining:
  max_walltime: 1
  gpu: true
ReferenceEvaluation:
  max_walltime: 0.3
  cpu_affinity: 'alternating'
  mpi_command: 'mpirun -np {}'
...
