---
container:
  engine: "apptainer"
  uri: "/home/sandervandenhaute/doctorate/source/psiflow/psiflow_python3.10_cuda_latest.sif"
ModelEvaluation:
  cores_per_worker: 2
  max_walltime: 0.3
  simulation_engine: 'openmm'
  gpu: false
ModelTraining:
  cores_per_worker: 4
  max_walltime: 1
  gpu: true
ReferenceEvaluation:
  cores_per_worker: 1
  max_walltime: 0.3
  cpu_affinity: 'block'
  #mpi_command: 'mpirun -np {}'
...
