---
ModelEvaluation:
  cores_per_worker: 2
  simulation_engine: 'openmm'
  gpu: false
ModelTraining:
  cores_per_worker: 4
  max_walltime: 1
  gpu: true
ReferenceEvaluation:
  cores_per_worker: 1
...
