---
container:
  engine: "apptainer"
  uri: "oras://ghcr.io/molmod/psiflow:3.0.2_python3.10_cuda"
ReferenceEvaluation:
  max_walltime: 20
  cores_per_worker: 128
  cpu_affinity: none
  SlurmProvider:
    partition: "cpu"
    account: "p******"
    nodes_per_block: 1
    cores_per_node: 128
    init_blocks: 0
    min_blocks: 0
    max_blocks: 98
    walltime: "48:00:00"
    exclusive: false
    scheduler_options: "#SBATCH --qos=default\n"
...
