---
ModelEvaluation:
  simulation_engine: 'openmm'
  gpu: false
  use_threadpool: true
ModelTraining:
  gpu: true
  use_threadpool: true
ReferenceEvaluation:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  mpi_command: 'mpirun -np 2 -x OMP_NUM_THREADS=1'  # cp2k on conda-forge comes with OpenMPI (not MPICH as in container)
  use_threadpool: true
...
