---
retries: 0
ModelEvaluation:
  gpu: false
  use_threadpool: true
  max_simulation_time: 0.4
ModelTraining:
  gpu: true
  use_threadpool: true
  max_training_time: 1
CP2K:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  launch_command: 'mpirun -np 2 -x OMP_NUM_THREADS=1 cp2k.psmp -i cp2k.inp'
  use_threadpool: true
CP2K_container:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  launch_command: 'apptainer exec -e --no-init oras://ghcr.io/molmod/cp2k:2023.2 /opt/entry.sh mpirun -np 2 -x OMP_NUM_THREADS=1 cp2k.psmp -i cp2k.inp'
  use_threadpool: true
GPAW:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  use_threadpool: true
GPAW_container:
  cores_per_worker: 2
  max_evaluation_time: 0.3
  launch_command: 'apptainer exec -e --no-init oras://ghcr.io/molmod/gpaw:24.1 /opt/entry.sh mpirun -np 2 gpaw python /opt/run_gpaw.py input.json'
  use_threadpool: true
...
