---
ModelEvaluation:
  cores_per_worker: 1
  simulation_engine: 'openmm'
  gpu: false
ModelTraining:
  cores_per_worker: 4
  max_walltime: 1
  gpu: true
ReferenceEvaluation:
 max_walltime: 0.3
 cores_per_worker: 1
 mpi_command: 'mpirun -np {}' # cp2k on conda-forge comes with OpenMPI (not MPICH as in container)
mode: 'workqueue'
...
