name: CI
run-name: pytest-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-py310:
    runs-on: ubuntu-latest
    container:
      options: --privileged
    steps:
      - name: Configure user namespaces
        run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          sudo mkdir -p /etc/subuid /etc/subgid
          sudo touch /etc/subuid /etc/subgid
          sudo usermod --add-subuids 10000-75535 runner
          sudo usermod --add-subgids 10000-75535 runner
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.0
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.5-0'
          environment-name: 'test-env'
          generate-run-shell: true
          create-args: >-
            python=3.10
            ndcctools==7.11.1
            py-plumed
            simple-dftd3
            dftd3-python
            pip
            -c conda-forge
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: install pip dependencies and execute pytest
        run: |
          pip install pyfftw colorcet wandb pandas plotly plumed 'numpy<2.0.0'
          pip install --no-cache-dir git+https://github.com/i-pi/i-pi.git@v3.0.0-beta4
          pip install git+https://github.com/acesuit/MACE.git@v0.3.5
          pip install 'psiflow[dev] @ git+https://github.com/molmod/psiflow.git'
          cd ${{ runner.temp }} && git clone https://github.com/molmod/psiflow
          cd psiflow
          export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
          apptainer exec oras://ghcr.io/molmod/cp2k:2024.1 ls
          apptainer exec oras://ghcr.io/molmod/gpaw:24.1 ls
          pytest --skip-gpu --psiflow-config=.github/threadpool.yaml tests/test_reference.py
        shell: micromamba-shell {0}
